version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node
    steps:
      - checkout

      - run: env | sort

      - run: bundle -v

      - restore_cache:
          keys:
            - learnenvoy-bundle-cache-v1-{{ checksum "Gemfile.lock" }}
            - learnenvoy-bundle-cache-v1-

      - run: pwd

      - run: make test

      - save_cache:
          key: learnenvoy-bundle-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
